# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      # see https://hub.docker.com/r/circleci/node/tags/
      - image: circleci/node:8.10.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: echo versions
          command: |
            node --version
            npm --version
            yarn --version

#      Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: yarn-install
          command: yarn --no-progress --pure-lockfile

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: rebuild node-sass
          command: npm rebuild node-sass

      - run:
          name: angular-test
          command: ./node_modules/.bin/ng test --environment=prod --sourcemap=false --single-run --progress=false --reporters=junit --browsers ChromeHeadless
          when: always

      - run:
          name: copy the karma test results
          command: |
            sudo mkdir -p --verbose ~/junit/karma
            sudo cp -v test-results.xml ~/junit/karma
          when: always

      - store_artifacts:
          path: ~/junit/karma/test-results.xml

      - run:
          name: angular-e2e
          command: ./node_modules/.bin/ng e2e
          when: always

      - run:
          name: copy the protractor test results
          command: |
            sudo mkdir -p --verbose ~/junit/protractor
            sudo cp -v e2e.xml ~/junit/protractor
          when: always

      - store_artifacts:
          path: ~/junit/protractor/e2e.xml

      - run:
          name: angular-lint
          command: ./node_modules/.bin/ng lint --format junit > tslint.xml
          when: always

      - run:
          name: copy the lint results
          command: |
            sudo mkdir -p --verbose ~/junit/tslint
            sudo cp -v tslint.xml ~/junit/tslint
          when: always

      - store_artifacts:
          path: ~/junit/tslint/tslint.xml

      # store the test results so they appear in Test Summary and Insights
      # https://circleci.com/docs/2.0/collect-test-data/
      - store_test_results:
          path: ~/junit

      - run:
          name: angular-build
          command: ./node_modules/.bin/ng build --prod --aot --no-progress










